apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: baas-app-multi-cluster
 namespace: argocd
spec:
 generators:
 - list:
     elements:
     - cluster: dev
       url: https://kubernetes.default.svc
       values:
         project: default
     - cluster: prod
       url: https://192.168.1.139:8443
       values:
         project: default
 template:
   metadata:
     name: 'cluster-{{cluster}}-baas-app'
   spec:
     project: default
     source:
       repoURL: https://github.com/Jared-Xu-Edi/argo-app-deploy.git
       targetRevision: HEAD
       path: appDeployDemo/demo1/{{cluster}}
     destination:
       server: '{{url}}'
       namespace: baas
     syncPolicy:
       automated:
        prune: true
        selfHeal: true
       syncOptions:
         - CreateNamespace=true