apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patches:
  - replica_count.yaml
  - resource_limit.yaml
# patchesStrategicMerge:
#   - env.yaml
images:
- name: jaredxu/baas-frontend
  newTag: v2
configMapGenerator:
- name: baas-config
  namespace: baas
  files:
    - configs/config.json