bases:
  - ../../base
patches:
  - replica_count.yaml
  - resource_limits.yaml
patchesStrategicMerge:
  - env.yaml
images:
- name: jaredxu/baas-frontend
  newTag: v2
configMapGenerator:
- name: baas-config
  namespace: baas
  files:
    - configs/config.json