apiVersion: v1
kind: Service
metadata:
  name: baas-frontend-service
  namespace: baas
spec:
  type: NodePort
  selector:
    app: baas-frontend
  ports:
  - port: 7777
    protocol: TCP
    targetPort: 8080
    nodePort: 30123
